services:
  # In production should use AWS RDS or similar managed database service
  wordpress:
    build:
      context: .
      dockerfile: wordpress.Dockerfile.prod
    ports: []
  nginx:
    ports:
      - "80:80" # Port 80 for HTTP is standard for production, however if used with AWS API Gateway or similar, may need to instead rely on port 443 for HTTPS.
      - "443:443"
