services:
  db:
    image: mariadb:10.6
    container_name: wordpress_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_net
  wordpress:
    # Build the custom WordPress image using our new Dockerfile
    build:
      context: .
      dockerfile: wordpress.Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    container_name: wordpress_app
    restart: always
    # Forces files created in wp-uploads folder have the correct ownership.
    user: "${UID}:${GID}"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      XDEBUG_MODE: "debug"
    volumes:
      - wordpress_data:/var/www/html
      - ./wordpress/wp-content/plugins/wc-extension:/var/www/html/wp-content/plugins/wc-extension
      - ./wordpress/wp-content/uploads:/var/www/html/wp-content/uploads
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - db
    networks:
      - wordpress_net
  nginx:
    build: .
    container_name: wordpress_nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - wordpress_data:/var/www/html:ro
      - ./wordpress/wp-content/uploads:/var/www/html/wp-content/uploads:ro
    depends_on:
      - wordpress
    networks:
      - wordpress_net

# Volumes for persistent data
volumes:
  db_data:
  # This named volume will be shared between the wordpress and nginx containers.
  wordpress_data:

# Network for inter-container communication
networks:
  wordpress_net:
